export { base } from './configurations/primitives/base';
export { jsdoc } from './configurations/primitives/jsdoc';
export { json } from './configurations/primitives/json';
export { prettier } from './configurations/primitives/prettier';
export { react } from './configurations/primitives/react';
export { regexp } from './configurations/primitives/regexp';
export { typescript } from './configurations/primitives/typescript';
export { typescriptNoTypeChecking } from './configurations/primitives/typescript-no-type-checking';
export { yaml } from './configurations/primitives/yaml';
