name: 'Handling feature dist-tag with github registry'

on:
  pull_request:
    branches:
      - main
    types:
      - opened # pr is created
      - reopened # pr is reopened
      - synchronize # pr got new commit

jobs:
  testing:
    permissions:
      pull-requests: write
    uses: beuluis/reusable-workflows/.github/workflows/node-qa-testing.yml@main
    with:
      skip_coverage_report: true
    secrets: inherit

  publish-feature-tag:
    needs: testing
    permissions:
      packages: write
    uses: beuluis/reusable-workflows/.github/workflows/github-npm-publish.yml@main
    with:
      dist_tag: ${{ github.head_ref }}
    secrets: inherit