name: 'Publish pack with latest dist-tag with npm registry'

on:
  release:
    types:
      - created

jobs:
  testing:
    uses: beuluis/reusable-workflows/.github/workflows/node-qa-testing.yml@main
    with:
      run_jest_coverage: false
      build_command: npm publish --dry-run
    secrets: inherit

  publish-npm:
    needs: testing
    uses: beuluis/reusable-workflows/.github/workflows/npm-publish.yml@main
    secrets: inherit