name: "Publish pack with next dist-tag with npm registry"

on:
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  testing:
    permissions:
      pull-requests: write
    uses: Beuterei/reusable-workflows/.github/workflows/node-qa-tests.yml@main
    secrets: inherit

  publish-npm:
    needs: testing
    uses: Beuterei/reusable-workflows/.github/workflows/package-publish.yml@main
    with:
      node_version: "22"
      dist_tag: "next"
    secrets: inherit
